### ISSUE TITLE
Check high values for SJ spring habitat 

### ISSUE THREAD

**Issue by ErinCain** [Reorienting-to-Recovery/DSMhabitat#23]
Please go back and review work for SJ habitat. Values still seem way higher than other watersheds.

**Comment by ErinCain** [comment]
@MaddeeRubenson Have you had a chance to work on this?

**Comment by MaddeeRubenson** [comment]
Results are looking good (per Rene, Mark) and a PR request will be issued to merge SJ habitat into R2R-main
