### ISSUE TITLE
update American river rearing habitat to the Water Forum flow to WUA relationship (currently used in VAs)

### ISSUE THREAD

**Issue by ErinCain** [Reorienting-to-Recovery/DSMhabitat#35]
- [ ]  Use [American Rearing WUA from VAs](https://github.com/FlowWest/va-habitat/blob/main/habitat-functions/American/data/LAR_Juv_Sal_WUA_2019-06-23.xlsx) in place of IFIMWUA for rearing habitat in DSMhabitat in data-raw/watersheds/american/american_river.Rmd
- [ ]  Update documentation to describe change in data, list new data sources.
- [ ]  Rerun markdown to save updated data in american_river.rmd
- [ ]  Rerun data-raw/cache_habitat.R file to resave new American river data.
- [ ] Rerun cache max habitat and cache baseline habitat scripts (ask / pair with Erin if questions on these ones)

**Comment by liz-fw** [comment]
update existing in branch: `american-updates`
update HRL in branch: `hrl-provided-data`

**Comment by liz-fw** [comment]
closed in PR
