### ISSUE TITLE
update Mokelumne baseline habitat

### ISSUE THREAD

**Issue by liz-fw** [Reorienting-to-Recovery/DSMhabitat#39]
[LMR_HSI_2015conditions.xlsx](https://github.com/user-attachments/files/16275701/LMR_HSI_2015conditions.xlsx)

Update the Mokelumne baseline habitat using this file from Michelle Workman in an e-mail Monday, July 8th:

"Please find attached the updated HSI curves for the Mokelumne using our 2015 lidar as baseline, and the HR&L suitability criteria. These are the most up to date for use in the SIT and in the HR&L modeling for the Mokelumne River."

**Comment by liz-fw** [comment]
update existing in branch: `mok-updates`
scale HRL in branch: `hrl-curves`

**Comment by MaddeeRubenson** [comment]
PR here: https://github.com/Reorienting-to-Recovery/DSMhabitat/pull/45
